In [1]:
import numpy as numpy
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [2]:
iris = datasets.load_iris()

In [3]:
iris.data.shape, iris.target.shape

((150, 4), (150,))

In [4]:
Atribut_Training, Atribut_Testing, Kelas_Training, Kelas_Testing = train_test_split(
    iris.data, iris.target,
    test_size=0.4, random_state=0
)

In [5]:
Atribut_Training.shape

(90, 4)

In [6]:
Atribut_Testing.shape

(60, 4)

In [7]:
Kelas_Training.shape

(90,)

In [8]:
Kelas_Testing.shape

(60,)

In [9]:
gnb = GaussianNB()

In [10]:
classifier = gnb.fit(Atribut_Training, Kelas_Training)

In [11]:
classifier.score(Atribut_Testing, Kelas_Testing)

0.9333333333333333

In [12]:
from sklearn.model_selection import cross_val_score

In [13]:
akurasi_cross_val = cross_val_score(classifier, iris.data, iris.target, cv=10)

In [14]:
akurasi_cross_val

array([0.93333333, 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.93333333, 0.86666667, 1.        , 1.        , 1.        ])

In [15]:
rerata_akurasi = akurasi_cross_val.mean()

In [16]:
rerata_akurasi

0.9533333333333334

PENGUJIAN KLASIFIKASI NAIVE BAYES

In [17]:
from sklearn.metrics import confusion_matrix, classification_report

In [18]:
Prediksi = classifier.predict(Atribut_Testing)
confusion_matrix(Prediksi, Kelas_Testing)

array([[16,  0,  0],
       [ 0, 23,  4],
       [ 0,  0, 17]], dtype=int64)

In [19]:
print(classification_report(Prediksi, Kelas_Testing))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.85      0.92        27
           2       0.81      1.00      0.89        17

    accuracy                           0.93        60
   macro avg       0.94      0.95      0.94        60
weighted avg       0.95      0.93      0.93        60



PENGUJIAN KLASIFIKASI NAIVE BAYES DENGAN CROSSVALIDATION

In [20]:
from sklearn.model_selection import cross_val_score, cross_val_predict

In [21]:
akurasi_cross_val = cross_val_score (classifier, iris.data, iris.target, cv=10)
akurasi_cross_val

array([0.93333333, 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.93333333, 0.86666667, 1.        , 1.        , 1.        ])

In [22]:
rerata_akurasi = akurasi_cross_val.mean()
rerata_akurasi

0.9533333333333334

In [23]:
y_pred = cross_val_predict(classifier, iris.data, iris.target, cv=10)
conf_mat = confusion_matrix(iris.target, y_pred)

In [24]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
conf_mat

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  4, 46]], dtype=int64)

In [26]:
print(classification_report(iris.target, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.92      0.94      0.93        50
           2       0.94      0.92      0.93        50

    accuracy                           0.95       150
   macro avg       0.95      0.95      0.95       150
weighted avg       0.95      0.95      0.95       150

