In [1]:
import numpy as numpy
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [2]:
Wine = datasets.load_wine()

In [3]:
Wine.data.shape, Wine.target.shape

((178, 13), (178,))

In [4]:
Atribut_Training, Atribut_Testing, Kelas_Training, Kelas_Testing = train_test_split(
    Wine.data, Wine.target,
    test_size=0.4, random_state=0
)

In [5]:
Atribut_Training.shape

(106, 13)

In [6]:
Atribut_Testing.shape

(72, 13)

In [7]:
Kelas_Training.shape

(106,)

In [8]:
Kelas_Testing.shape

(72,)

In [9]:
gnb = GaussianNB()
classifier = gnb.fit(Atribut_Training, Kelas_Training)

In [10]:
classifier.score(Atribut_Testing, Kelas_Testing)

0.9444444444444444

In [11]:
from sklearn.model_selection import cross_val_score

In [12]:
akurasi_cross_val = cross_val_score(classifier, Wine.data, Wine.target, cv=5)

In [13]:
akurasi_cross_val

array([0.94444444, 0.97222222, 0.97222222, 0.94285714, 1.        ])

In [14]:
rerata_akurasi = akurasi_cross_val.mean()
rerata_akurasi

0.9663492063492063

In [16]:
akurasi_cross_val = cross_val_score(classifier, Wine.data, Wine.target, cv=10)

In [17]:
akurasi_cross_val

array([0.94444444, 1.        , 1.        , 0.94444444, 0.94444444,
       1.        , 1.        , 0.94444444, 1.        , 1.        ])

In [18]:
rerata_akurasi = akurasi_cross_val.mean()
rerata_akurasi

0.9777777777777779

PENGUJIAN KLASIFIKASI MENGGUNAKAN NAIVE BAYES


In [23]:
from sklearn.metrics import confusion_matrix, classification_report

In [24]:
Prediksi = classifier.predict(Atribut_Testing)
confusion_matrix(Prediksi, Kelas_Testing)

array([[22,  2,  0],
       [ 0, 27,  0],
       [ 0,  2, 19]], dtype=int64)

In [25]:
print(classification_report(Prediksi, Kelas_Testing))

              precision    recall  f1-score   support

           0       1.00      0.92      0.96        24
           1       0.87      1.00      0.93        27
           2       1.00      0.90      0.95        21

    accuracy                           0.94        72
   macro avg       0.96      0.94      0.95        72
weighted avg       0.95      0.94      0.95        72



PENGUJIAN KLASIFIKASI NAIVE BAYES DENGAN CROSSVALIDATION

In [26]:
from sklearn.model_selection import cross_val_score, cross_val_predict

In [27]:
akurasi_cross_val = cross_val_score (classifier, Wine.data, Wine.target, cv=5)
akurasi_cross_val

array([0.94444444, 0.97222222, 0.97222222, 0.94285714, 1.        ])

In [28]:
rerata_akurasi = akurasi_cross_val.mean()
rerata_akurasi

0.9663492063492063

In [29]:
y_pred = cross_val_predict(classifier, Wine.data, Wine.target, cv=5)
conf_mat = confusion_matrix(Wine.target, y_pred)

In [30]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [31]:
conf_mat

array([[56,  3,  0],
       [ 1, 68,  2],
       [ 0,  0, 48]], dtype=int64)

In [33]:
print(classification_report(Wine.target, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.95      0.97        59
           1       0.96      0.96      0.96        71
           2       0.96      1.00      0.98        48

    accuracy                           0.97       178
   macro avg       0.97      0.97      0.97       178
weighted avg       0.97      0.97      0.97       178



In [34]:
akurasi_cross_val = cross_val_score (classifier, Wine.data, Wine.target, cv=10)
akurasi_cross_val

array([0.94444444, 1.        , 1.        , 0.94444444, 0.94444444,
       1.        , 1.        , 0.94444444, 1.        , 1.        ])

In [35]:
rerata_akurasi = akurasi_cross_val.mean()
rerata_akurasi

0.9777777777777779

In [36]:
y_pred = cross_val_predict(classifier, Wine.data, Wine.target, cv=10)
conf_mat = confusion_matrix(Wine.target, y_pred)

In [37]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [38]:
conf_mat

array([[57,  2,  0],
       [ 0, 69,  2],
       [ 0,  0, 48]], dtype=int64)

In [40]:
print(classification_report(Wine.target, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.97      0.98        59
           1       0.97      0.97      0.97        71
           2       0.96      1.00      0.98        48

    accuracy                           0.98       178
   macro avg       0.98      0.98      0.98       178
weighted avg       0.98      0.98      0.98       178

