In [1]:
import numpy as numpy
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [2]:
Cancer = datasets.load_breast_cancer()

In [3]:
Cancer.data.shape, Cancer.target.shape

((569, 30), (569,))

In [4]:
Atribut_Training, Atribut_Testing, Kelas_Training, Kelas_Testing = train_test_split(
    Cancer.data, Cancer.target,
    test_size=0.4, random_state=0
)

In [5]:
Atribut_Training.shape

(341, 30)

In [6]:
Atribut_Testing.shape

(228, 30)

In [7]:
Kelas_Training.shape

(341,)

In [8]:
Kelas_Testing.shape

(228,)

In [9]:
gnb = GaussianNB()

In [10]:
classifier = gnb.fit(Atribut_Training, Kelas_Training)

In [11]:
classifier.score(Atribut_Testing, Kelas_Testing)

0.9298245614035088

In [12]:
from sklearn.model_selection import cross_val_score

In [14]:
akurasi_cross_val = cross_val_score(classifier, Cancer.data, Cancer.target, cv=5)

In [15]:
akurasi_cross_val

array([0.92105263, 0.92105263, 0.94736842, 0.94736842, 0.95575221])

In [16]:
rerata_akurasi = akurasi_cross_val.mean()

In [17]:
rerata_akurasi

0.9385188635305075

In [18]:
akurasi_cross_val = cross_val_score(classifier, Cancer.data, Cancer.target, cv=10)

In [19]:
akurasi_cross_val

array([0.94736842, 0.87719298, 0.89473684, 0.92982456, 0.94736842,
       0.96491228, 0.92982456, 0.96491228, 0.94736842, 0.96428571])

In [20]:
rerata_akurasi = akurasi_cross_val.mean()

In [21]:
rerata_akurasi

0.9367794486215537

PENGUJIAN KLASIFIKASI MENGGUNAKAN NAIVE BAYES

In [22]:
from sklearn.metrics import confusion_matrix, classification_report

In [23]:
Prediksi = classifier.predict(Atribut_Testing)
confusion_matrix(Prediksi, Kelas_Testing)

array([[ 74,   7],
       [  9, 138]], dtype=int64)

In [24]:
print(classification_report(Prediksi, Kelas_Testing))

              precision    recall  f1-score   support

           0       0.89      0.91      0.90        81
           1       0.95      0.94      0.95       147

    accuracy                           0.93       228
   macro avg       0.92      0.93      0.92       228
weighted avg       0.93      0.93      0.93       228



PENGUJIAN KLASIFIKASI NAIVE BAYES DENGAN CROSSVALIDATION

In [25]:
from sklearn.model_selection import cross_val_score, cross_val_predict

In [27]:
akurasi_cross_val = cross_val_score (classifier, Cancer.data, Cancer.target, cv=5)
akurasi_cross_val

array([0.92105263, 0.92105263, 0.94736842, 0.94736842, 0.95575221])

In [28]:
rerata_akurasi = akurasi_cross_val.mean()
rerata_akurasi

0.9385188635305075

In [30]:
y_pred = cross_val_predict(classifier, Cancer.data, Cancer.target, cv=5)
conf_mat = confusion_matrix(Cancer.target, y_pred)

In [31]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,

In [32]:
conf_mat

array([[188,  24],
       [ 11, 346]], dtype=int64)

In [34]:
print(classification_report(Cancer.target, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.89      0.91       212
           1       0.94      0.97      0.95       357

    accuracy                           0.94       569
   macro avg       0.94      0.93      0.93       569
weighted avg       0.94      0.94      0.94       569



In [35]:
akurasi_cross_val = cross_val_score (classifier, Cancer.data, Cancer.target, cv=10)
akurasi_cross_val

array([0.94736842, 0.87719298, 0.89473684, 0.92982456, 0.94736842,
       0.96491228, 0.92982456, 0.96491228, 0.94736842, 0.96428571])

In [36]:
rerata_akurasi = akurasi_cross_val.mean()
rerata_akurasi

0.9367794486215537

In [37]:
y_pred = cross_val_predict(classifier, Cancer.data, Cancer.target, cv=10)
conf_mat = confusion_matrix(Cancer.target, y_pred)

In [38]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,

In [39]:
conf_mat

array([[188,  24],
       [ 12, 345]], dtype=int64)

In [41]:
print(classification_report(Cancer.target, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.89      0.91       212
           1       0.93      0.97      0.95       357

    accuracy                           0.94       569
   macro avg       0.94      0.93      0.93       569
weighted avg       0.94      0.94      0.94       569

